---
- hosts: all
  gather_facts: False
  remote_user: root
  tasks:
  - name: filter&disable useless service
    template:
      src: templates/default_services_tuning.sh
      dest: /tmp/ansible/default_services_tuning.sh
      owner: root
      group: root
      mode: 700
  - name: execute script
    shell: /tmp/ansible/default_services_tuning.sh
    args:
        creates: /tmp/ansible/services.log
