---
- hosts: all
  gather_facts: False
  remote_user: root
  tasks:
  - name: create a temporary directory
    file:
      dest: /tmp/ansible
      state: directory
      mode: 0755
  - name: filter&disable useless service
    copy:
      src: files/default_services_tuning.sh
      dest: /tmp/ansible/default_services_tuning.sh
      owner: root
      group: root
      mode: 0700
  - name: execute script
    shell: /tmp/ansible/default_services_tuning.sh
    args:
        creates: /tmp/ansible/services.log
