---
- hosts: all
  gather_facts: Fasle
  remote_user: root
  tasks:
  - name: disable default users
    replace:
      name: /etc/passwd
      regexp: "{{ item.regexp }}"
      replace: "{{ item.line }}"
    with_items:
      - { regexp: '^bin', line: '#bin' }
      - { regexp: '^daemon', line: '#daemon' }
      - { regexp: '^adm', line: '#adm' }
      - { regexp: '^lp', line: '#lp' }
      - { regexp: '^sync', line: '#sync' }
      - { regexp: '^shutdown', line: '#shutdown' }
      - { regexp: '^halt', line: '#halt' }
      - { regexp: '^mail', line: '#mail' }
      - { regexp: '^uucp', line: '#uucp' }
      - { regexp: '^operator', line: '#operator' }
      - { regexp: '^games', line: '#games' }
      - { regexp: '^gopher', line: '#gopher' }
      - { regexp: '^ftp', line: '#ftp' }
      - { regexp: '^nobody', line: '#nobody' }
      - { regexp: '^dbus', line: '#dbus' }
      - { regexp: '^rpc', line: '#rpc' }
      - { regexp: '^vcsa', line: '#vcsa' }
      - { regexp: '^abrt', line: '#abrt' }
      - { regexp: '^haldaemon', line: '#haldaemon' }
      - { regexp: '^ntp', line: '#ntp' }
      - { regexp: '^saslauth', line: '#saslauth' }
      - { regexp: '^postfix', line: '#postfix' }
      - { regexp: '^nfsnobody', line: '#nfsnobody' }
      - { regexp: '^sshd', line: '#sshd' }
      - { regexp: '^tcpdump', line: '#tcpdump' }
