---
- hosts: all
  gather_facts: False
  remote_user: root
  tasks:
  - name: check mount point
    template:
      src: files/filesystem_tuning.sh
      dest: /tmp/ansible/filesystem_tuning.sh
      owner: root
      group: root
      mode: 0700
  - name: execute script
    shell: /tmp/ansible/filesystem_tuning.sh
    args:
        creates: /tmp/ansible/filesystem_tuning.log
