---
- hosts: all
  gather_facts: False
  remote_user: root
  tasks:
  - name: disable selinux
    lineinfile:
      name: /etc/selinux/config
      regexp: '^SELINUX='
      line: 'SELINUX=disabled'
  - name: modify /etc/host.conf
    replace:
      name: /etc/host.conf
      regexp: "^multi on(?!\norder)"
      replace: "multi on\norder hosts,bind\nnospoof on"
