---
- hosts: all
  gather_facts: False
  remote_user: root
  tasks:
  - name: check whether swap is on or not
    shell: cat /proc/swaps | wc -l
    register: result
  - name: disable swap
    shell: swapoff -a
    when: result.stdout != '1'
