---
- hosts: all
  gather_facts: False
  remote_user: root
  tasks:
  - name: set timezone
    file:
      src: /usr/share/zoneinfo/Asia/Shanghai
      dest: /etc/localtime
      state: link
      force: yes
  - name: set /etc/sysconfig/clock
    replace: 
      name: /etc/sysconfig/clock
      regexp: '^ZONE=(?!"Asia/Shanghai")'
      replace: "ZONE=\"Asia/Shanghai\"\nUTC=false"
  - name: set /etc/adjtime
    replace:
      name: /etc/adjtime
      regexp: 'UTC'
      replace: 'LOCAL'
